In [1]:
a,b=6,0
try:
    g=a/b
except ZeroDivisionError as s:
    print(s)
else:           #using else 
    print(g)

division by zero


In [2]:
try:
    a=int(input("enter a positive integer: "))
    if a<=0:
        raise ValueError("that is not a positive number!") # using keyword (raise) -> throws 
    print("the value is  ",a)
    
except ValueError as ve:
    print(ve)
else: 
    print("the value is ",a)

enter a positive integer: 5
the value is   5
the value is  5


In [3]:
#   -------New Topic ----------->>>>> numpy



import numpy as np


In [4]:
# 1d array

a1=np.array([3,6,7,9])

In [5]:
a1

array([3, 6, 7, 9])

In [6]:
a1.dtype

dtype('int32')

In [8]:
a1.sum()

25

In [9]:
a2=np.arange(1,23,2)

In [10]:
a2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [11]:
a3=np.linspace(1,20,6)

In [12]:
a3

array([ 1. ,  4.8,  8.6, 12.4, 16.2, 20. ])

In [13]:
a3.shape

(6,)

In [15]:
# 2d array
ar2=np.array([3,6,5,4,8,3,2,5]).reshape(4,2)      ####  ---  row ------  coloum ->shape  ---  reshape


In [16]:
ar2

array([[3, 6],
       [5, 4],
       [8, 3],
       [2, 5]])

In [19]:
ar3=np.array([1,2,3,4,5,6,7,8]).reshape(2,4)

In [20]:
# matrix multiplucation 

res=ar2.dot(ar3)

In [21]:
res

array([[33, 42, 51, 60],
       [25, 34, 43, 52],
       [23, 34, 45, 56],
       [27, 34, 41, 48]])

In [23]:
res.transpose()

array([[33, 25, 23, 27],
       [42, 34, 34, 34],
       [51, 43, 45, 41],
       [60, 52, 56, 48]])

In [24]:
ar2[1][1]

4

In [26]:
ar2[2:,1:4]   #[row:row,coloum:coloum]

array([[3],
       [5]])